project:
  type: website
  resources: 
    - "*.pdf"

website:
  title: "Kenneth Blake Vernon"
  description: "My personal (professional, maybe?) website."
  site-url: "https://www.kbvernon.io"
  search: false
  
  favicon: "/images/favicon.png"
  twitter-card:
    image: "/images/green_grass_valley-meta.jpg"
  open-graph:
    image: "/images/green_grass_valley-meta.jpg"
  
  navbar:
    title: "KBV"
    left:
      - text: "About"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Presentations"
        href: presentations.qmd
    right:
      - icon: envelope
        href: mailto:Kenneth.Vernon@colorado.edu
      - icon: github
        href: https://github.com/kbvernon/
      - text: "{{< iconify fa6-brands:orcid size=lg >}}"
        href: https://orcid.org/0000-0003-0098-5092
      - text: "{{< iconify academicons:google-scholar size=lg >}}"
        href: https://scholar.google.com/citations?user=2PE4za4AAAAJ&hl=en
      - text: "{{< iconify academicons:cv size=lg >}}"
        href: cv-vernon.pdf

  page-footer:
    center: |
      &copy; 2022 Kenneth B. Vernon. Powered by [Quarto](https://quarto.org/).\
      The source code for this site can be found at its <a href="https://github.com/kbvernon/Blake_down">Github repository</a>.

format:
  html:
    theme: 
      - simplex
      - custom.scss
    mainfont: sans-serif
    page-layout: article
    toc: false
    minimal: true
    smooth-scroll: true

editor: source

execute: 
  echo: false
  error: false
  warning: false
  output: asis
