baseURL = "/"
languageCode = "en-us"
title = "Kenneth Blake Vernon"
theme = "minimal"
# disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "^blake_", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
    author = "KB Vernon"
    description = ""
    githubUsername = "#"
    accent = "#CC0000"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "&copy; 2020 Kenneth B. Vernon. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)."

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/research/"
    name = "Research"
    weight = 3
    
[[menu.main]]
    url = "/vitae/"
    name = "Vitae"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:kenneth.b.vernon@utah.edu"
    name = "fa fa-envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/kbvernon/"
    name = "fa fa-github"
    weight = 2

[[menu.icon]]
    url = "https://orcid.org/0000-0003-0098-5092"
    name = "ai ai-orcid"
    weight = 3

[[menu.icon]]
    url = "https://scholar.google.com/citations?user=2PE4za4AAAAJ&hl=en"
    name = "ai ai-google-scholar"
    weight = 4
    
[[menu.icon]]
    url = "/additional_files/blake_vitae.pdf"
    name = "ai ai-cv"
    weight = 5    
