---
title: "Publications"
---

<!-- To embed Academicicons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

```{r, echo = FALSE}
source("setup.R")
source("cv_tables.R")
```

```{r}

collection <- here("data", "collections") %>% jsonlite::read_json(simplifyVector = TRUE)

zotero <- here("data", "zotero") %>% jsonlite::read_json(simplifyVector = TRUE)

bib <- cv_get_bib(zotero, collection)

```

### Peer-reviewed journal articles

```{r}

bib %>% 
  filter(groups == "Article") %>% 
  mutate(ref = glue::glue(
    
    "{author} ({year}). {title}. _{journal}_ {volume} ({number}): {pages}. DOI: {doi} <br><br>"
    
    )) %>% 
  select(year, ref) %>% 
  cv_bibble()

```

<br>

### Book reviews

```{r}

bib %>%
  filter(groups == "Review") %>%
  mutate(ref = glue::glue(
    
    "{author} ({year}). {title}. _{journal}_ {volume} ({number}): {pages}. DOI: {doi} <br><br>"
    
    )) %>% 
  select(year, ref) %>% 
  cv_bibble()

```

<br>

### Technical reports

```{r}

bib %>% 
  filter(groups == "Report") %>% 
  mutate(ref = glue::glue(
    
    "{author} ({year}). {title}. Report submitted to the {institution}, {address}. <br><br>"
    
    )) %>% 
  select(year, ref) %>% 
  cv_bibble()

```

