---
title: publications
author: K.B. Vernon
date: '2020-04-07'
slug: publications
categories: []
tags: []
description: ''
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

library(glue)
library(here)
library(jsonlite)
library(kableExtra)
library(knitr)
library(RefManageR)
library(tidyverse)

options(knitr.kable.NA = "")

```

```{r}

source(here("style/blake_cv_style.R"))

```

```{r}

collection <- jsonlite::read_json(here("data/collections"), simplifyVector = TRUE)

zotero <- jsonlite::read_json(here("data/zotero"), simplifyVector = TRUE)

bib <- cv_bibble(zotero, collection)

```

### Peer-reviewed journal articles

```{r}

bib %>% 
  filter(groups == "Article") %>% 
  mutate(ref = glue::glue(
    
    "{author} ({year}). {title}. _{journal}_ {volume} ({number}): {pages}. DOI: {doi} <br><br>"
    
    )) %>% 
  select(year, ref) %>% 
  cv_kable(bib = TRUE)

```

<br>

### Book reviews

```{r}

bib %>%
  filter(groups == "Review") %>%
  mutate(ref = glue::glue(
    
    "{author} ({year}). {title}. _{journal}_ {volume} ({number}): {pages}. DOI: {doi} <br><br>"
    
    )) %>% 
  select(year, ref) %>% 
  cv_kable(bib = TRUE)

```

<br>

### Technical reports

```{r}

bib %>% 
  filter(groups == "Report") %>% 
  mutate(ref = glue::glue(
    
    "{author} ({year}). {title}. Report submitted to the {institution}, {address}. <br><br>"
    
    )) %>% 
  select(year, ref) %>% 
  cv_kable(bib = TRUE)

```
