---
format:
  html:
    toc: false
    page-layout: article
---

:::{.small .text-muted}
LAST UPDATED  
`r Sys.Date()` 

DISCLAIMER  
While I stand by what I say here, please keep in mind, it's a snapshot of my evolving beliefs about pedagogy *at a particular time and place*, not an unwavering declaration of faith, set in stone, never to change.  
:::

## Teaching Statement

I like to think of my teaching and mentoring as just one small part of a much larger and much more ambitious social-engineering project called higher education. There are many roles such a project can and often does play in a society, but three in particular stand out for me. First, and perhaps most obviously, it facilitates the inter-generational transfer of our accumulated knowledge and wisdom. Second, it promotes the civic virtues that we rely on as a free and open society, like openness to new ideas, courage in pursuing the truth, and respect for those we might disagree with, to name just a few. Third, it serves as an instrument of justice, of fairness and equality, whether that be in our economy, our environment, or our social lives. I believe that these ends - knowledge, justice, and virtue - are coincident in practice, meaning they rise and fall as one. Together with the arts, they are also the primary engines of human flourishing.  

Invoking such mighty goals, of course, is easy, pursuing them, not so much. I mean, it's not like signposts reading "Justice, this way" are lying about pointing the way. Still, the goals of education would seem to recommend a certain pedagogy or prescription for teaching that I would put like this:  

> **Try as far as possible to meet students where they are, to speak their language**.[^1]  

I would go so far as to say this is the core idea that animates everything I do as an educator. It also entails a number of more concrete rules for action, which I now enumerate with examples from my own experience.  

**Be sensitive to the diverse backgrounds, experiences, and interests of students.** You cannot possibly meet students where they are if you do not know where that is, so I conduct a number of early assignments and tests with my students, including a pre-course assessment, that are designed to provide information about their current knowledge and interests. I also use informal, through-course assessments (what normal people would call small talk) to learn more about them. Basically, I just try to treat them like they're adults.  

**Re-contextualize ideas, then re-contextualize them some more.** Underlying the injunction to speak your student's language is the old rationalist idea that learning a new concept, like learning a new word, involves a lot of translation back and forth into a more familiar idiom. For me, in practice, that means using lots of examples, placing the concept in a more familiar context, seeing how it gets used there and what its use entails, then slowly walking it through less and less familiar settings, all the while asking students to think about and discuss its shifting implications. Naturally, that includes traditional lecture, but I also offer students lots of opportunities to try out translating ideas through lab and other exercises involving problems from the ordinary and everyday to the ethnographic and archaeological.  

**Manage expectations, both yours and your students, don't demand too much or too little!** Translating new ideas into your own words can be difficult, often frustratingly so. Over time, though, the translating gets easier, eventually becoming unnecessary. But, that's not something that just happens over night. Usually, you have to *immerse* yourself in a new idea, live with it day by day, just as one would need to do to really learn a new language. This is a point I try to impress upon my students at every occasion, especially when they are feeling discouraged, like they aren't learning the materials fast enough, are getting left behind, or not living up to expectations. In such circumstances, I tell them that one class will not an expert make, that expertise might not even be the goal! Sometimes a basic familiarity will suffice for what they really want to learn or do, and that's OK.  

**Invite them into the conversation.** Immersion through active learning, learning through doing. Mentoring through research.

From the Fall of 2018 to the Spring of 2022, I served as the Assistant Director of the University of Utah Archaeological Center. While my responsibilities there included managing all UUAC-led field and lab projects, the vast majority of my time was devoted to mentoring undergraduate researchers both in their own independent projects and in their contributions to the UUAC. Over those four years, I had the great fortune of working with 24 undergraduate researchers on 23 separate projects (some student initiated, others ongoing UUAC projects). Of those, I helped 6 receive Undergraduate Research Opportunities Program grants totaling \$9,000. For 10 others, I secured small grants and stipends from the U’s Global Change and Sustainability Center, the US Forest Service, the Anthropology Department, and the National Science Foundation, totaling approximately \$10,000, to support them as undergraduate research assistants on UUAC-related projects. 16 of the 24 undergraduate researchers were from protected categories, having diverse backgrounds and interests. The projects they led and contributed to were also extremely similar to the one being pursued here, involving many of the same methods required to collect, organize, summarize, visualize, and analyze data.

[^1]: Framing it in this way is actually something I picked up from one of Neil deGrasse Tyson's Reddit AMAs, specifically [an answer he gave to a high school teacher](https://www.reddit.com/r/IAmA/comments/mateq/comment/c2zgn1d/?utm_source=share&utm_medium=web2x&context=3) looking for guidance on how to impart to students the thrill and joy of actually *doing* science. The relevant part of his answer is this: "a goal as teacher, perhaps ought to include knowing as much as you possibly can about pop culture and referencing it at every turn as you teach the syllabus." It may seem superficial, but it's actually quite reasonable, as popular culture - for better or worse - provides a set of shared metaphors, analogies, narratives, slang terms, jokes, and memes, among other things, that people can use to communicate their beliefs and values in a way that gives them a reasonable shot at being understood. 


