---
format:
  html:
    toc: false
    page-layout: article
---

```{r}
#| echo: false

today <- Sys.Date()

```

::: {.disclaimer .small .text-muted}
LAST UPDATED  
`r today`

DISCLAIMER  
My teaching philosophy is inspired by the American style of [pragmatism](https://en.wikipedia.org/wiki/Pragmatism) 
I learned from my old friend and mentor, Norbert Schedler, a former Lutheran 
minister who stumbled upon the heretical writings of intellectuals like 
Nietzsche and Darwin and basically never looked back. He got his PhD at 
Princeton, taught at Purdue and Berkeley, and then decided the academic rat race 
wasn't for him, so he took a position at a small teaching college in the middle 
of nowhere, Arkansas, where he could focus on his family and his teaching. He 
would often say that our primary duty as educators and intellectuals and even as 
citizens is to "keep the conversation going!" You can think of the following 
statement as trying to articulate how I keep the conversation going in my own 
teaching and mentoring, and for that matter, in my research, too. 
:::

**THIS IS STILL A WORK IN PROGRESS!**

## Teaching Statement

I like to think of my teaching and mentoring as just one small part of a much
larger and much more ambitious social-engineering project called higher
education. There are many roles such a project can and often does play in a
society, but three in particular stand out for me. First, and perhaps most
obviously, it facilitates the inter-generational transfer of our accumulated
knowledge and wisdom. Second, it promotes the civic virtues that we rely on as a
free and open society, like openness to new ideas, courage in pursuing the
truth, and respect for those we might disagree with, to name just a few. Third,
it serves as an instrument of justice, of fairness and equality, whether that be
in our economy, our environment, or our social lives. I believe that these
ends - knowledge, justice, and virtue - are coincident in practice, meaning they
rise and fall as one. Together with the arts, they are also the primary engines
of human flourishing.

Invoking such mighty goals, of course, is easy, pursuing them, not so much. I
mean, it's not like signposts reading "Justice, this way" are lying about
pointing the way. Still, the goals of education would seem to recommend a
certain pedagogy or prescription for teaching that I would put like this:

> **Try to meet students where they are, to speak their
> language**.[^1]

[^1]: Framing it in this way is actually something I picked up from one of Neil
    deGrasse Tyson's Reddit AMAs, specifically [an answer he gave to a high
    school
    teacher](https://www.reddit.com/r/IAmA/comments/mateq/comment/c2zgn1d/?utm_source=share&utm_medium=web2x&context=3)
    looking for guidance on how to impart to students the thrill and joy of
    actually *doing* science. The relevant part of his answer is this: "a goal
    as teacher, perhaps ought to include knowing as much as you possibly can
    about pop culture and referencing it at every turn as you teach the
    syllabus." It may seem superficial, but it's actually quite reasonable, as
    popular culture - for better or worse - provides a set of shared metaphors,
    analogies, narratives, slang terms, jokes, and memes, among other things,
    that people can use to communicate their beliefs and values in a way that
    gives them a reasonable shot at being understood.

I would go so far as to say this is the core idea that animates everything I do
as an educator. It also entails a number of more concrete rules for action,
which I now enumerate with examples from my own experience.

**Be sensitive to the diverse backgrounds, experiences, and interests of
students.** You cannot possibly meet students where they are if you do not know
where that is, so I conduct a number of early assignments and tests with my
students, including a pre-course assessment, that are designed to provide
information about their current knowledge and interests. I also use informal,
through-course assessments (what normal people would call small talk) to learn
more about them. Basically, I just try to treat them like they're adults.

**Re-contextualize ideas, then re-contextualize them some more.** Underlying the
injunction to speak your student's language is the old rationalist idea that
learning a new concept, like learning a new word, involves a lot of translation
back and forth into a more familiar idiom. For me, in practice, that means using
lots of examples, placing the concept in a more familiar context, seeing how it
gets used there and what its use entails, then slowly walking it through less
and less familiar settings, all the while asking students to think about and
discuss its shifting implications. Naturally, that includes traditional lecture,
but I also offer students lots of opportunities to try out translating ideas
through lab and other exercises involving problems from the ordinary and
everyday to the ethnographic and archaeological.

**Manage expectations, both yours and your students, don't demand too much or
too little!** Translating new ideas into your own words can be difficult, often
frustratingly so. Over time, though, the translating gets easier, eventually
becoming unnecessary. But, that's not something that just happens over night.
Usually, you have to *immerse* yourself in a new idea, live with it day by day,
just as one would need to do to really learn a new language. This is a point I
try to impress upon my students at every occasion, especially when they are
feeling discouraged, like they aren't learning the materials fast enough, are
getting left behind, or not living up to expectations. In such circumstances, I
tell them that one class will not an expert make, that expertise might not even
be the goal! Sometimes a basic familiarity will suffice for what they really
want to learn or do, and that's OK.

**Invite them into the conversation.** This is my preferred way of describing
what most folks in the academy would call "active learning" as it emphasizes 
that the learning in this case is participatory, meaning the student does not 
just learn how to, say, move liquids with a pipette or calibrate a scale, but to 
engage critically with the scientific process, to step up and make their own 
moves in the wider conversation of science. As a graduate student at the 
University of Utah, I had the good fortune to mentor a lot of undergraduate 
researchers - dozens of them, actually - from all walks of life, mostly through 
my role as Assistant Director of the Archaeological Center. It's easily one of 
the most rewarding things I did as a graduate student at the U, and something I 
look forward to continuing into the future.

**But, also have some perspective.** In the social sciences and humanities, we 
need to be more cognizant of the possibility that encouraging students to pursue 
careers in our disciplines might do little more than subject them to a life of 
penury. The best way we can do that is by teaching "transferable skills." For 
me, that mostly means teaching them data science skills, specifically 
quantitative reasoning or statistics and computer programming.
